# fly.toml app configuration file generated for demospace1 on 2024-06-12T00:26:52-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'demospace'
primary_region = 'sjc'
kill_signal = 'SIGTERM'
kill_timeout = 360

[[services]]
  

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
